export const ENVS = {
	MONGO_USER: 'MONGO_USER',
	MONGO_PASSWORD: 'MONGO_PASSWORD',
	MONGO_HOST: 'MONGO_HOST',
	MONGO_PORT: 'MONGO_PORT',
	MONGO_DB: 'MONGO_DB',
	MONGO_AUTH_DB: 'MONGO_AUTH_DB',
} as const;
